# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NEW_app_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_app_dialog(object):
    def setupUi(self, app_dialog):
        app_dialog.setObjectName("app_dialog")
        app_dialog.resize(500, 470)
        app_dialog.setMinimumSize(QtCore.QSize(500, 470))
        app_dialog.setMaximumSize(QtCore.QSize(500, 470))
        self.buttonBox = QtWidgets.QDialogButtonBox(app_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(140, 420, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.name_label = QtWidgets.QLabel(app_dialog)
        self.name_label.setGeometry(QtCore.QRect(20, 20, 83, 27))
        self.name_label.setMinimumSize(QtCore.QSize(83, 0))
        self.name_label.setObjectName("name_label")
        self.exe_label = QtWidgets.QLabel(app_dialog)
        self.exe_label.setGeometry(QtCore.QRect(20, 60, 83, 27))
        self.exe_label.setMinimumSize(QtCore.QSize(83, 0))
        self.exe_label.setMaximumSize(QtCore.QSize(16777215, 28))
        self.exe_label.setObjectName("exe_label")
        self.name_input = QtWidgets.QLineEdit(app_dialog)
        self.name_input.setGeometry(QtCore.QRect(170, 20, 311, 27))
        self.name_input.setObjectName("name_input")
        self.exe_input = QtWidgets.QLineEdit(app_dialog)
        self.exe_input.setGeometry(QtCore.QRect(170, 60, 311, 27))
        self.exe_input.setObjectName("exe_input")
        self.parameters_label = QtWidgets.QLabel(app_dialog)
        self.parameters_label.setGeometry(QtCore.QRect(20, 100, 83, 27))
        self.parameters_label.setMinimumSize(QtCore.QSize(83, 0))
        self.parameters_label.setMaximumSize(QtCore.QSize(16777215, 28))
        self.parameters_label.setObjectName("parameters_label")
        self.parameters_input = QtWidgets.QLineEdit(app_dialog)
        self.parameters_input.setGeometry(QtCore.QRect(170, 100, 311, 27))
        self.parameters_input.setObjectName("parameters_input")
        self.location_label = QtWidgets.QLabel(app_dialog)
        self.location_label.setEnabled(True)
        self.location_label.setGeometry(QtCore.QRect(20, 290, 191, 31))
        self.location_label.setMinimumSize(QtCore.QSize(83, 0))
        self.location_label.setObjectName("location_label")
        self.location_combobox = QtWidgets.QComboBox(app_dialog)
        self.location_combobox.setEnabled(True)
        self.location_combobox.setGeometry(QtCore.QRect(331, 290, 150, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.location_combobox.sizePolicy().hasHeightForWidth())
        self.location_combobox.setSizePolicy(sizePolicy)
        self.location_combobox.setMinimumSize(QtCore.QSize(150, 31))
        self.location_combobox.setMaximumSize(QtCore.QSize(150, 31))
        self.location_combobox.setObjectName("location_combobox")
        self.desktop_label = QtWidgets.QLabel(app_dialog)
        self.desktop_label.setGeometry(QtCore.QRect(20, 250, 83, 31))
        self.desktop_label.setMinimumSize(QtCore.QSize(83, 0))
        self.desktop_label.setObjectName("desktop_label")
        self.desktop_combobox = QtWidgets.QComboBox(app_dialog)
        self.desktop_combobox.setGeometry(QtCore.QRect(430, 250, 51, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desktop_combobox.sizePolicy().hasHeightForWidth())
        self.desktop_combobox.setSizePolicy(sizePolicy)
        self.desktop_combobox.setMinimumSize(QtCore.QSize(51, 31))
        self.desktop_combobox.setMaximumSize(QtCore.QSize(51, 31))
        self.desktop_combobox.setObjectName("desktop_combobox")
        self.monitor_label = QtWidgets.QLabel(app_dialog)
        self.monitor_label.setGeometry(QtCore.QRect(20, 210, 81, 31))
        self.monitor_label.setMinimumSize(QtCore.QSize(81, 0))
        self.monitor_label.setObjectName("monitor_label")
        self.monitor_combobox = QtWidgets.QComboBox(app_dialog)
        self.monitor_combobox.setGeometry(QtCore.QRect(430, 210, 51, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(51)
        sizePolicy.setVerticalStretch(31)
        sizePolicy.setHeightForWidth(self.monitor_combobox.sizePolicy().hasHeightForWidth())
        self.monitor_combobox.setSizePolicy(sizePolicy)
        self.monitor_combobox.setMinimumSize(QtCore.QSize(51, 31))
        self.monitor_combobox.setObjectName("monitor_combobox")
        self.placement_label = QtWidgets.QLabel(app_dialog)
        self.placement_label.setGeometry(QtCore.QRect(20, 170, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.placement_label.setFont(font)
        self.placement_label.setObjectName("placement_label")
        self.test_btn = QtWidgets.QPushButton(app_dialog)
        self.test_btn.setGeometry(QtCore.QRect(20, 423, 101, 26))
        self.test_btn.setMinimumSize(QtCore.QSize(0, 26))
        self.test_btn.setMaximumSize(QtCore.QSize(16777215, 26))
        self.test_btn.setObjectName("test_btn")
        self.window_checkBox = QtWidgets.QCheckBox(app_dialog)
        self.window_checkBox.setGeometry(QtCore.QRect(19, 140, 191, 22))
        self.window_checkBox.setChecked(True)
        self.window_checkBox.setObjectName("window_checkBox")
        self.splash_checkBox = QtWidgets.QCheckBox(app_dialog)
        self.splash_checkBox.setGeometry(QtCore.QRect(19, 330, 161, 22))
        self.splash_checkBox.setChecked(False)
        self.splash_checkBox.setObjectName("splash_checkBox")
        self.uses_existing_checkBox = QtWidgets.QCheckBox(app_dialog)
        self.uses_existing_checkBox.setGeometry(QtCore.QRect(19, 360, 411, 22))
        self.uses_existing_checkBox.setChecked(False)
        self.uses_existing_checkBox.setObjectName("uses_existing_checkBox")

        self.retranslateUi(app_dialog)
        self.buttonBox.accepted.connect(app_dialog.accept)
        self.buttonBox.rejected.connect(app_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(app_dialog)
